spring.application.name=demo

# JWT secret for demo (override in production)
jwt.secret=change-me-for-prod

server.port=${PORT:8080}

# file uploads
file.upload-dir=uploads

# SQL Server settings for development/production
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;trustServerCertificate=true;characterEncoding=UTF-8;useUnicode=true;sendStringParametersAsUnicode=true
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=sa
#spring.datasource.password=123
#
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true


# // dev
# spring.datasource.url=jdbc:postgresql://localhost:5432/nhakhoaDB
# spring.datasource.username=postgres
# spring.datasource.password=12345678

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.properties.hibernate.jdbc.batch_size=20
# spring.jpa.properties.hibernate.order_inserts=true
# spring.jpa.properties.hibernate.order_updates=true


# //server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

# ////////////
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# UTF-8 Encoding
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Static resources
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.mvc.static-path-pattern=/uploads/**

